### ISSUE TITLE
Unwanted Text in return OBJECT

### ISSUE THREAD

**Issue by sarwaralamini** [symisc/pixlab-php#1]
![carbon (5)](https://github.com/symisc/pixlab-php/assets/35809682/3ce95c22-1c04-4a95-9617-225166ed8c64)
Please see the unwanted "P" inside MRZ_RAW_TEXT object for which its only returning "P". Inside "MRZ_RAW_TEXT " can not be extracted.
Thanks

**Comment by symisc** [comment]
Hi, this is the raw MRZ text extracted from the Passport image using the [DOCSCAN](https://pixlab.io/cmd?id=docscan) API endpoint. You do not need to rely on this field. All parsed Passports fields such as _Full Name, Date of Birth, Expiry Date_, etc. are located on the fields object of the returned JSON array. Refer to the [DOCSCAN API endpoint documentation](https://pixlab.io/cmd?id=docscan) for additional information with code samples.
